[project]
name = "fcu-class-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bs4>=0.0.2",
    "ddddocr>=1.5.6",
    "lxml>=6.0.1",
    "pyside6>=6.9.2",
    "requests>=2.32.5",
]
